<?php
error_reporting(0);
$list = curl_get('http://www.360kan.com/dianshi/list');
$list1 = curl_get('http://www.360kan.com/dianying/list.php');
$list2 = curl_get('http://www.360kan.com/dongman/list.php');
$list3 = curl_get('http://www.360kan.com/zongyi/list.php');
$lzz = '#<a class="js-tongjip" href="http://www.360kan.com/dianshi/list\\?year=all\\&area\\=all\\&act\\=all\\&cat\\=(.*?)" target="_self">(.*?)</a>#is';
$lzz1 = '# <a class="js-tongjip" href="http://www.360kan.com/dianshi/list\\?cat\\=all\\&area=all\\&act\\=all\\&year\\=(.*?)" target="_self">(.*?)</a>#is';
$lzz2 = '#<a class="js-tongjip" href="http://www.360kan.com/dianshi/list\\?cat\\=all\\&year\\=all\\&act\\=all\\&area\\=(.*?)" target="_self">(.*?)</a>#is';
$lzz3 = '#<a class="js-tongjip" href="http://www.360kan.com/dianshi/list\\?cat\\=all\\&year\\=all\\&area\\=all\\&act\\=(.*?)" target="_self">(.*?)</a>#is';
$lzzmv = '#<a class="js-tongjip" href="http://www.360kan.com/dianying/list.php\\?year=all\\&area=all\\&act=all\\&cat=(.*?)" target="_self">(.*?)</a>#is';
$lzzmv1 = '#<a class="js-tongjip" href="http://www.360kan.com/dianying/list.php\\?cat\\=all\\&area=all\\&act\\=all\\&year\\=(.*?)" target="_self">(.*?)</a>#is';
$lzzmv2 = '#<a class="js-tongjip" href="http://www.360kan.com/dianying/list.php\\?cat\\=all\\&year\\=all\\&act\\=all\\&area\\=(.*?)" target="_self">(.*?)</a>#is';
$lzzmv3 = '#<a class="js-tongjip" href="http://www.360kan.com/dianying/list.php\\?cat\\=all\\&year\\=all\\&area\\=all\\&act\\=(.*?)" target="_self">(.*?)</a>#is';
$lzzdm = '#<a class="js-tongjip" href="http://www.360kan.com/dongman/list.php\\?year=all\\&area=all\\&cat=(.*?)" target="_self">(.*?)</a>#is';
$lzzdm1 = '#<a class="js-tongjip" href="http://www.360kan.com/dongman/list.php\\?cat\\=all\\&area=all\\&year\\=(.*?)" target="_self">(.*?)</a>#is';
$lzzdm2 = '#<a class="js-tongjip" href="http://www.360kan.com/dongman/list.php\\?cat\\=all\\&year\\=all\\&area\\=(.*?)" target="_self">(.*?)</a>#is';
$lzzzy = '#<a class="js-tongjip" href="http://www.360kan.com/zongyi/list.php\\?act=all\\&area=all\\&cat=(.*?)" target="_self">(.*?)</a>#is';
$lzzzy1 = '#<a class="js-tongjip" href="http://www.360kan.com/zongyi/list.php\\?cat\\=all\\&area=all\\&act\\=(.*?)" target="_self">(.*?)</a>#is';
$lzzzy2 = '#<a class="js-tongjip" href="http://www.360kan.com/zongyi/list.php\\?cat\\=all\\&act\\=all\\&area\\=(.*?)" target="_self">(.*?)</a>#is';
preg_match_all($lzz, $list, $larr);
preg_match_all($lzz1, $list, $larr1);
preg_match_all($lzz2, $list, $larr2);
preg_match_all($lzz3, $list, $larr3);
preg_match_all($lzzmv, $list1, $larrmv);
preg_match_all($lzzmv1, $list1, $larrmv1);
preg_match_all($lzzmv2, $list1, $larrmv2);
preg_match_all($lzzmv3, $list1, $larrmv3);
preg_match_all($lzzdm, $list2, $larrdm);
preg_match_all($lzzdm1, $list2, $larrdm1);
preg_match_all($lzzdm2, $list2, $larrdm2);
preg_match_all($lzzdm3, $list2, $larrdm3);
preg_match_all($lzzzy, $list3, $larrzy);
preg_match_all($lzzzy1, $list3, $larrzy1);
preg_match_all($lzzzy2, $list3, $larrzy2);
preg_match_all($lzzzy3, $list3, $larrzy3);
$cat = $larr[1];
$cat1 = $larr1[1];
$cat2 = $larr2[1];
$cat3 = $larr3[1];
$name = $larr[2];
$name1 = $larr1[2];
$name2 = $larr2[2];
$name3 = $larr3[2];
$mcat = $larrmv[1];
$mcat1 = $larrmv1[1];
$mcat2 = $larrmv2[1];
$mcat3 = $larrmv3[1];
$mname = $larrmv[2];
$mname1 = $larrmv1[2];
$mname2 = $larrmv2[2];
$mname3 = $larrmv3[2];
$dmcat = $larrdm[1];
$dmcat1 = $larrdm[1];
$dmcat2 = $larrdm[1];
$dmname = $larrdm[2];
$dmname1 = $larrdm1[2];
$dmname2 = $larrdm2[2];
$zycat = $larrzy[1];
$zycat1 = $larrzy1[1];
$zycat2 = $larrzy2[1];
$zyname = $larrzy[2];
$zyname1 = $larrzy1[2];
$zyname2 = $larrzy2[2];
